apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app.kubernetes.io/name: myapp
    env: production
spec:
  containers:
  - name: nginx-container
    image: nginx #your app image name
    ports:
      - containerPort: 80